clone_folder: c:\projects\azure-rest-api-specs

environment:
  access_token:
    secure: JWSy9tPo2eoTYpPQplvokf4IiVk6onNBbWwAs6nNWWyQ2JaO+MRAg/QzbJnTjpUm

before_build:
  - cd ..
  - if exist azure-docs-rest-apis rmdir /s /q azure-docs-rest-apis
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "vscopbld@microsoft.com"
  - git config --global user.name "OpenPublishBuild"
  - git clone -q --branch=CIIntegration https://github.com/Azure/azure-docs-rest-apis.git
  
build_script:
  - ps: azure-docs-rest-apis\Scripts\build.ps1

on_success:
  - cd azure-docs-rest-apis
  - git add .
  - git diff --quiet --exit-code --cached || git commit -m "Rest document Updated by CI" && git push origin CIIntegration
  - appveyor AddMessage "Rest document Updated"
