clone_folder: c:\projects\azure-rest-api-specs

environment:
  opbuilduseremail: "hxyjessie@gmail.com"
  opbuilduser: "Huang Xueyuan"
  access_token:
    secure: JWSy9tPo2eoTYpPQplvokf4IiVk6onNBbWwAs6nNWWyQ2JaO+MRAg/QzbJnTjpUm

before_build:
  - ps: |
        if($env:APPVEYOR_SCHEDULED_BUILD -or ($env:APPVEYOR_REPO_COMMIT_AUTHOR -eq $env:opbuilduser))
        {
          $env:shouldRun=true
        }
        if($env:shouldRun)
        {
          echo "test before_build"
        }
  
build_script:
  - ps: echo "test build_script"

on_success:
  - if "%shouldRun%" (
        echo "test on_success"
    )
