clone_folder: c:\projects\azure-rest-api-specs

environment:
  opbuilduseremail: "hxyjessie@gmail.com"
  access_token:
    secure: JWSy9tPo2eoTYpPQplvokf4IiVk6onNBbWwAs6nNWWyQ2JaO+MRAg/QzbJnTjpUm

before_build:
  - ps: |
        echo $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL
        echo $opbuilduseremail
        if($env:APPVEYOR_SCHEDULED_BUILD -or ($env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL -eq $opbuilduseremail))
        {
          echo "test before_build"
        }
  
build_script:
  - ps: echo "test build_script"

on_success:
  - echo %APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL%
  - if "%APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL%" == "hxyjessie@gmail.com" (
      echo "test on_success"
    )
